version: '3'
services:
  db:
    container_name: pgDb
    restart: always
    image: circleci/postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./src:/usr/local/src
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=postgres
    depends_on:
      - db
    volumes:
      - .:/app